# Global Configurations
global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'broadway_sns_playground'

# Targets to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'elixir_app'
    static_configs:
      - targets: ['host.docker.internal:9568']